#!/usr/bin/env python3
import json
import os

# Comprehensive mapping of ISO alpha-3 codes to country names and continents
country_data = {
    # Africa
    'DZA': {'name': 'Algeria', 'continent': 'Africa'},
    'AGO': {'name': 'Angola', 'continent': 'Africa'},
    'BEN': {'name': 'Benin', 'continent': 'Africa'},
    'BWA': {'name': 'Botswana', 'continent': 'Africa'},
    'BFA': {'name': 'Burkina Faso', 'continent': 'Africa'},
    'BDI': {'name': 'Burundi', 'continent': 'Africa'},
    'CPV': {'name': 'Cape Verde', 'continent': 'Africa'},
    'CAF': {'name': 'Central African Republic', 'continent': 'Africa'},
    'TCD': {'name': 'Chad', 'continent': 'Africa'},
    'COM': {'name': 'Comoros', 'continent': 'Africa'},
    'COG': {'name': 'Republic of the Congo', 'continent': 'Africa'},
    'COD': {'name': 'Democratic Republic of the Congo', 'continent': 'Africa'},
    'CIV': {'name': 'Ivory Coast', 'continent': 'Africa'},
    'DJI': {'name': 'Djibouti', 'continent': 'Africa'},
    'EGY': {'name': 'Egypt', 'continent': 'Africa'},
    'GNQ': {'name': 'Equatorial Guinea', 'continent': 'Africa'},
    'ERI': {'name': 'Eritrea', 'continent': 'Africa'},
    'SWZ': {'name': 'Eswatini', 'continent': 'Africa'},
    'ETH': {'name': 'Ethiopia', 'continent': 'Africa'},
    'GAB': {'name': 'Gabon', 'continent': 'Africa'},
    'GMB': {'name': 'Gambia', 'continent': 'Africa'},
    'GHA': {'name': 'Ghana', 'continent': 'Africa'},
    'GIN': {'name': 'Guinea', 'continent': 'Africa'},
    'GNB': {'name': 'Guinea-Bissau', 'continent': 'Africa'},
    'KEN': {'name': 'Kenya', 'continent': 'Africa'},
    'LSO': {'name': 'Lesotho', 'continent': 'Africa'},
    'LBR': {'name': 'Liberia', 'continent': 'Africa'},
    'LBY': {'name': 'Libya', 'continent': 'Africa'},
    'MDG': {'name': 'Madagascar', 'continent': 'Africa'},
    'MWI': {'name': 'Malawi', 'continent': 'Africa'},
    'MLI': {'name': 'Mali', 'continent': 'Africa'},
    'MRT': {'name': 'Mauritania', 'continent': 'Africa'},
    'MUS': {'name': 'Mauritius', 'continent': 'Africa'},
    'MYT': {'name': 'Mayotte', 'continent': 'Africa'},
    'MAR': {'name': 'Morocco', 'continent': 'Africa'},
    'MOZ': {'name': 'Mozambique', 'continent': 'Africa'},
    'NAM': {'name': 'Namibia', 'continent': 'Africa'},
    'NER': {'name': 'Niger', 'continent': 'Africa'},
    'NGA': {'name': 'Nigeria', 'continent': 'Africa'},
    'REU': {'name': 'Réunion', 'continent': 'Africa'},
    'RWA': {'name': 'Rwanda', 'continent': 'Africa'},
    'SHN': {'name': 'Saint Helena, Ascension and Tristan da Cunha', 'continent': 'Africa'},
    'STP': {'name': 'São Tomé and Príncipe', 'continent': 'Africa'},
    'SEN': {'name': 'Senegal', 'continent': 'Africa'},
    'SYC': {'name': 'Seychelles', 'continent': 'Africa'},
    'SLE': {'name': 'Sierra Leone', 'continent': 'Africa'},
    'SOM': {'name': 'Somalia', 'continent': 'Africa'},
    'ZAF': {'name': 'South Africa', 'continent': 'Africa'},
    'SSD': {'name': 'South Sudan', 'continent': 'Africa'},
    'SDN': {'name': 'Sudan', 'continent': 'Africa'},
    'TZA': {'name': 'Tanzania', 'continent': 'Africa'},
    'TGO': {'name': 'Togo', 'continent': 'Africa'},
    'TUN': {'name': 'Tunisia', 'continent': 'Africa'},
    'UGA': {'name': 'Uganda', 'continent': 'Africa'},
    'ZMB': {'name': 'Zambia', 'continent': 'Africa'},
    'ZWE': {'name': 'Zimbabwe', 'continent': 'Africa'},

    # Asia
    'AFG': {'name': 'Afghanistan', 'continent': 'Asia'},
    'ARE': {'name': 'United Arab Emirates', 'continent': 'Asia'},
    'ARM': {'name': 'Armenia', 'continent': 'Asia'},
    'AZE': {'name': 'Azerbaijan', 'continent': 'Asia'},
    'BGD': {'name': 'Bangladesh', 'continent': 'Asia'},
    'BHR': {'name': 'Bahrain', 'continent': 'Asia'},
    'BRN': {'name': 'Brunei', 'continent': 'Asia'},
    'BTN': {'name': 'Bhutan', 'continent': 'Asia'},
    'KHM': {'name': 'Cambodia', 'continent': 'Asia'},
    'CHN': {'name': 'China', 'continent': 'Asia'},
    'CXR': {'name': 'Christmas Island', 'continent': 'Asia'},
    'CCK': {'name': 'Cocos (Keeling) Islands', 'continent': 'Asia'},
    'GEO': {'name': 'Georgia', 'continent': 'Asia'},
    'HKG': {'name': 'Hong Kong', 'continent': 'Asia'},
    'IND': {'name': 'India', 'continent': 'Asia'},
    'IDN': {'name': 'Indonesia', 'continent': 'Asia'},
    'IRN': {'name': 'Iran', 'continent': 'Asia'},
    'IRQ': {'name': 'Iraq', 'continent': 'Asia'},
    'ISR': {'name': 'Israel', 'continent': 'Asia'},
    'JOR': {'name': 'Jordan', 'continent': 'Asia'},
    'JPN': {'name': 'Japan', 'continent': 'Asia'},
    'KAZ': {'name': 'Kazakhstan', 'continent': 'Asia'},
    'KWT': {'name': 'Kuwait', 'continent': 'Asia'},
    'KGZ': {'name': 'Kyrgyzstan', 'continent': 'Asia'},
    'LAO': {'name': 'Laos', 'continent': 'Asia'},
    'LBN': {'name': 'Lebanon', 'continent': 'Asia'},
    'MAC': {'name': 'Macau', 'continent': 'Asia'},
    'MYS': {'name': 'Malaysia', 'continent': 'Asia'},
    'MDV': {'name': 'Maldives', 'continent': 'Asia'},
    'MNG': {'name': 'Mongolia', 'continent': 'Asia'},
    'MMR': {'name': 'Myanmar', 'continent': 'Asia'},
    'NPL': {'name': 'Nepal', 'continent': 'Asia'},
    'PRK': {'name': 'North Korea', 'continent': 'Asia'},
    'OMN': {'name': 'Oman', 'continent': 'Asia'},
    'PAK': {'name': 'Pakistan', 'continent': 'Asia'},
    'PSE': {'name': 'Palestine', 'continent': 'Asia'},
    'PHL': {'name': 'Philippines', 'continent': 'Asia'},
    'QAT': {'name': 'Qatar', 'continent': 'Asia'},
    'SAU': {'name': 'Saudi Arabia', 'continent': 'Asia'},
    'SGP': {'name': 'Singapore', 'continent': 'Asia'},
    'KOR': {'name': 'South Korea', 'continent': 'Asia'},
    'LKA': {'name': 'Sri Lanka', 'continent': 'Asia'},
    'SYR': {'name': 'Syria', 'continent': 'Asia'},
    'TWN': {'name': 'Taiwan', 'continent': 'Asia'},
    'TJK': {'name': 'Tajikistan', 'continent': 'Asia'},
    'THA': {'name': 'Thailand', 'continent': 'Asia'},
    'TLS': {'name': 'Timor-Leste', 'continent': 'Asia'},
    'TKM': {'name': 'Turkmenistan', 'continent': 'Asia'},
    'TUR': {'name': 'Turkey', 'continent': 'Asia'},
    'UZB': {'name': 'Uzbekistan', 'continent': 'Asia'},
    'VNM': {'name': 'Vietnam', 'continent': 'Asia'},
    'YEM': {'name': 'Yemen', 'continent': 'Asia'},

    # Europe
    'ALA': {'name': 'Åland Islands', 'continent': 'Europe'},
    'ALB': {'name': 'Albania', 'continent': 'Europe'},
    'AND': {'name': 'Andorra', 'continent': 'Europe'},
    'AUT': {'name': 'Austria', 'continent': 'Europe'},
    'BLR': {'name': 'Belarus', 'continent': 'Europe'},
    'BEL': {'name': 'Belgium', 'continent': 'Europe'},
    'BIH': {'name': 'Bosnia and Herzegovina', 'continent': 'Europe'},
    'BGR': {'name': 'Bulgaria', 'continent': 'Europe'},
    'HRV': {'name': 'Croatia', 'continent': 'Europe'},
    'CYP': {'name': 'Cyprus', 'continent': 'Europe'},
    'CZE': {'name': 'Czech Republic', 'continent': 'Europe'},
    'DNK': {'name': 'Denmark', 'continent': 'Europe'},
    'EST': {'name': 'Estonia', 'continent': 'Europe'},
    'FIN': {'name': 'Finland', 'continent': 'Europe'},
    'FRA': {'name': 'France', 'continent': 'Europe'},
    'DEU': {'name': 'Germany', 'continent': 'Europe'},
    'GIB': {'name': 'Gibraltar', 'continent': 'Europe'},
    'GRC': {'name': 'Greece', 'continent': 'Europe'},
    'GGY': {'name': 'Guernsey', 'continent': 'Europe'},
    'HUN': {'name': 'Hungary', 'continent': 'Europe'},
    'ISL': {'name': 'Iceland', 'continent': 'Europe'},
    'IRL': {'name': 'Ireland', 'continent': 'Europe'},
    'IMN': {'name': 'Isle of Man', 'continent': 'Europe'},
    'ITA': {'name': 'Italy', 'continent': 'Europe'},
    'JEY': {'name': 'Jersey', 'continent': 'Europe'},
    'LVA': {'name': 'Latvia', 'continent': 'Europe'},
    'LIE': {'name': 'Liechtenstein', 'continent': 'Europe'},
    'LTU': {'name': 'Lithuania', 'continent': 'Europe'},
    'LUX': {'name': 'Luxembourg', 'continent': 'Europe'},
    'MLT': {'name': 'Malta', 'continent': 'Europe'},
    'MDA': {'name': 'Moldova', 'continent': 'Europe'},
    'MCO': {'name': 'Monaco', 'continent': 'Europe'},
    'MNE': {'name': 'Montenegro', 'continent': 'Europe'},
    'NLD': {'name': 'Netherlands', 'continent': 'Europe'},
    'MKD': {'name': 'North Macedonia', 'continent': 'Europe'},
    'NOR': {'name': 'Norway', 'continent': 'Europe'},
    'POL': {'name': 'Poland', 'continent': 'Europe'},
    'PRT': {'name': 'Portugal', 'continent': 'Europe'},
    'ROU': {'name': 'Romania', 'continent': 'Europe'},
    'RUS': {'name': 'Russia', 'continent': 'Europe'},
    'SMR': {'name': 'San Marino', 'continent': 'Europe'},
    'SRB': {'name': 'Serbia', 'continent': 'Europe'},
    'SVK': {'name': 'Slovakia', 'continent': 'Europe'},
    'SVN': {'name': 'Slovenia', 'continent': 'Europe'},
    'ESP': {'name': 'Spain', 'continent': 'Europe'},
    'SJM': {'name': 'Svalbard and Jan Mayen', 'continent': 'Europe'},
    'SWE': {'name': 'Sweden', 'continent': 'Europe'},
    'CHE': {'name': 'Switzerland', 'continent': 'Europe'},
    'UKR': {'name': 'Ukraine', 'continent': 'Europe'},
    'GBR': {'name': 'United Kingdom', 'continent': 'Europe'},
    'VAT': {'name': 'Vatican City', 'continent': 'Europe'},

    # North America
    'ABW': {'name': 'Aruba', 'continent': 'North America'},
    'AIA': {'name': 'Anguilla', 'continent': 'North America'},
    'ATG': {'name': 'Antigua and Barbuda', 'continent': 'North America'},
    'BHS': {'name': 'Bahamas', 'continent': 'North America'},
    'BLM': {'name': 'Saint Barthélemy', 'continent': 'North America'},
    'BLZ': {'name': 'Belize', 'continent': 'North America'},
    'BMU': {'name': 'Bermuda', 'continent': 'North America'},
    'BES': {'name': 'Bonaire, Sint Eustatius and Saba', 'continent': 'North America'},
    'CAN': {'name': 'Canada', 'continent': 'North America'},
    'CYM': {'name': 'Cayman Islands', 'continent': 'North America'},
    'CRI': {'name': 'Costa Rica', 'continent': 'North America'},
    'CUB': {'name': 'Cuba', 'continent': 'North America'},
    'CUW': {'name': 'Curaçao', 'continent': 'North America'},
    'DMA': {'name': 'Dominica', 'continent': 'North America'},
    'DOM': {'name': 'Dominican Republic', 'continent': 'North America'},
    'SLV': {'name': 'El Salvador', 'continent': 'North America'},
    'GLP': {'name': 'Guadeloupe', 'continent': 'North America'},
    'GRD': {'name': 'Grenada', 'continent': 'North America'},
    'GTM': {'name': 'Guatemala', 'continent': 'North America'},
    'HTI': {'name': 'Haiti', 'continent': 'North America'},
    'HND': {'name': 'Honduras', 'continent': 'North America'},
    'JAM': {'name': 'Jamaica', 'continent': 'North America'},
    'MAF': {'name': 'Saint Martin', 'continent': 'North America'},
    'MEX': {'name': 'Mexico', 'continent': 'North America'},
    'MSR': {'name': 'Montserrat', 'continent': 'North America'},
    'NIC': {'name': 'Nicaragua', 'continent': 'North America'},
    'PAN': {'name': 'Panama', 'continent': 'North America'},
    'PRI': {'name': 'Puerto Rico', 'continent': 'North America'},
    'KNA': {'name': 'Saint Kitts and Nevis', 'continent': 'North America'},
    'LCA': {'name': 'Saint Lucia', 'continent': 'North America'},
    'SPM': {'name': 'Saint Pierre and Miquelon', 'continent': 'North America'},
    'VCT': {'name': 'Saint Vincent and the Grenadines', 'continent': 'North America'},
    'SXM': {'name': 'Sint Maarten', 'continent': 'North America'},
    'TCA': {'name': 'Turks and Caicos Islands', 'continent': 'North America'},
    'TTO': {'name': 'Trinidad and Tobago', 'continent': 'North America'},
    'USA': {'name': 'United States', 'continent': 'North America'},
    'VGB': {'name': 'British Virgin Islands', 'continent': 'North America'},
    'VIR': {'name': 'U.S. Virgin Islands', 'continent': 'North America'},
    'GRL': {'name': 'Greenland', 'continent': 'North America'},
    'MTQ': {'name': 'Martinique', 'continent': 'North America'},

    # South America
    'ARG': {'name': 'Argentina', 'continent': 'South America'},
    'BOL': {'name': 'Bolivia', 'continent': 'South America'},
    'BRA': {'name': 'Brazil', 'continent': 'South America'},
    'CHL': {'name': 'Chile', 'continent': 'South America'},
    'COL': {'name': 'Colombia', 'continent': 'South America'},
    'ECU': {'name': 'Ecuador', 'continent': 'South America'},
    'FLK': {'name': 'Falkland Islands', 'continent': 'South America'},
    'GUF': {'name': 'French Guiana', 'continent': 'South America'},
    'GUY': {'name': 'Guyana', 'continent': 'South America'},
    'PRY': {'name': 'Paraguay', 'continent': 'South America'},
    'PER': {'name': 'Peru', 'continent': 'South America'},
    'SUR': {'name': 'Suriname', 'continent': 'South America'},
    'URY': {'name': 'Uruguay', 'continent': 'South America'},
    'VEN': {'name': 'Venezuela', 'continent': 'South America'},

    # Oceania
    'ASM': {'name': 'American Samoa', 'continent': 'Oceania'},
    'AUS': {'name': 'Australia', 'continent': 'Oceania'},
    'COK': {'name': 'Cook Islands', 'continent': 'Oceania'},
    'FJI': {'name': 'Fiji', 'continent': 'Oceania'},
    'FSM': {'name': 'Micronesia', 'continent': 'Oceania'},
    'GUM': {'name': 'Guam', 'continent': 'Oceania'},
    'KIR': {'name': 'Kiribati', 'continent': 'Oceania'},
    'MHL': {'name': 'Marshall Islands', 'continent': 'Oceania'},
    'MNP': {'name': 'Northern Mariana Islands', 'continent': 'Oceania'},
    'NCL': {'name': 'New Caledonia', 'continent': 'Oceania'},
    'NZL': {'name': 'New Zealand', 'continent': 'Oceania'},
    'NIU': {'name': 'Niue', 'continent': 'Oceania'},
    'NFK': {'name': 'Norfolk Island', 'continent': 'Oceania'},
    'PLW': {'name': 'Palau', 'continent': 'Oceania'},
    'PNG': {'name': 'Papua New Guinea', 'continent': 'Oceania'},
    'PCN': {'name': 'Pitcairn', 'continent': 'Oceania'},
    'WSM': {'name': 'Samoa', 'continent': 'Oceania'},
    'SLB': {'name': 'Solomon Islands', 'continent': 'Oceania'},
    'TKL': {'name': 'Tokelau', 'continent': 'Oceania'},
    'TON': {'name': 'Tonga', 'continent': 'Oceania'},
    'TUV': {'name': 'Tuvalu', 'continent': 'Oceania'},
    'UMI': {'name': 'United States Minor Outlying Islands', 'continent': 'Oceania'},
    'VUT': {'name': 'Vanuatu', 'continent': 'Oceania'},
    'WLF': {'name': 'Wallis and Futuna', 'continent': 'Oceania'},
    'PYF': {'name': 'French Polynesia', 'continent': 'Oceania'},

    # Antarctica and special regions
    'ATA': {'name': 'Antarctica', 'continent': 'Antarctica'},
    'ATF': {'name': 'French Southern Territories', 'continent': 'Africa'},
    'BVT': {'name': 'Bouvet Island', 'continent': 'Atlantic Ocean'},
    'HMD': {'name': 'Heard Island and McDonald Islands', 'continent': 'Indian Ocean'},
    'IOT': {'name': 'British Indian Ocean Territory', 'continent': 'Asia'},
    'SGS': {'name': 'South Georgia and the South Sandwich Islands', 'continent': 'South Atlantic'},
    'ESH': {'name': 'Western Sahara', 'continent': 'Africa'},
    'FRO': {'name': 'Faroe Islands', 'continent': 'Europe'},
}

# Get all flag files from the assets directory
flag_dir = 'assets/flags/svg'
flag_files = [f.replace('.svg', '') for f in os.listdir(flag_dir) if f.endswith('.svg')]

# Build continents dictionary
continents = {}
countries = []

for code in flag_files:
    if code in country_data:
        country = country_data[code]
        countries.append({
            'id': code,
            'name': country['name'],
            'continent': country['continent'],
            'flagPath': f'../../../{flag_dir}/{code}.svg'
        })

        continent = country['continent']
        if continent not in continents:
            continents[continent] = []
        continents[continent].append(code)

# Create final data structure
data = {
    'continents': continents,
    'countries': countries
}

# Write to countries.json
output_path = 'game-modes/geography-games/world-flag-championships/data/countries.json'
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Created {output_path} with {len(countries)} countries across {len(continents)} continents')

# Debug info
missing_flags = set(flag_files) - set(country_data.keys())
if missing_flags:
    print(f'Missing countries for these flag codes: {sorted(missing_flags)[:10]}...')
